default_ecosystem: base

networks:
  custom:
    - name: base
      ecosystem: base
      chain_id: 8453

geth:
  base:
    mainnet:
      uri: https://rpc.ankr.com/base

blockscout:
  base:
    mainnet:
      uri: https://api.basescan.org

plugins:
  - name: base
    version: 0.7.1
  - name: optimism
    version: 0.7.3
  - name: blockscout
    version: git+https://github.com/mariuspod/ape-blockscout@24eea1eef759987eba08de0e419d3da5f033c125

